# Generated by Django 4.0.4 on 2022-06-01 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=30)),
                ('points', models.IntegerField()),
                ('finch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='main_app.finch')),
            ],
        ),
    ]
